//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryStore.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryStoreEntities : DbContext
    {
        public InventoryStoreEntities()
            : base("name=InventoryStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Brands> tbl_Brands { get; set; }
        public virtual DbSet<tbl_Categories> tbl_Categories { get; set; }
        public virtual DbSet<tbl_Groups> tbl_Groups { get; set; }
        public virtual DbSet<tbl_Orders> tbl_Orders { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }
        public virtual DbSet<tbl_Stores> tbl_Stores { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual int delete_Store(Nullable<int> store_Id)
        {
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_Store", store_IdParameter);
        }
    
        public virtual ObjectResult<Search_Store_Result> Search_Store(Nullable<int> store_Id)
        {
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Store_Result>("Search_Store", store_IdParameter);
        }
    
        public virtual int Update_Store(string store_Name, Nullable<int> store_status, Nullable<int> store_Id)
        {
            var store_NameParameter = store_Name != null ?
                new ObjectParameter("Store_Name", store_Name) :
                new ObjectParameter("Store_Name", typeof(string));
    
            var store_statusParameter = store_status.HasValue ?
                new ObjectParameter("store_status", store_status) :
                new ObjectParameter("store_status", typeof(int));
    
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Store", store_NameParameter, store_statusParameter, store_IdParameter);
        }
    
        public virtual ObjectResult<ViewAll_Stores_Result> ViewAll_Stores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAll_Stores_Result>("ViewAll_Stores");
        }
    }
}
