//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryStore.DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InventoryStoreEntityConnection : DbContext
    {
        public InventoryStoreEntityConnection()
            : base("name=InventoryStoreEntityConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_Brands> tbl_Brands { get; set; }
        public virtual DbSet<tbl_Categories> tbl_Categories { get; set; }
        public virtual DbSet<tbl_Groups> tbl_Groups { get; set; }
        public virtual DbSet<tbl_Orders> tbl_Orders { get; set; }
        public virtual DbSet<tbl_Products> tbl_Products { get; set; }
        public virtual DbSet<tbl_Stores> tbl_Stores { get; set; }
        public virtual DbSet<tbl_Supplier> tbl_Supplier { get; set; }
        public virtual DbSet<tbl_Users> tbl_Users { get; set; }
    
        public virtual int delete_Store(Nullable<int> store_Id)
        {
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_Store", store_IdParameter);
        }
    
        public virtual ObjectResult<Search_Store_Result> Search_Store(Nullable<int> store_Id)
        {
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Store_Result>("Search_Store", store_IdParameter);
        }
    
        public virtual int Update_Store(string store_Name, Nullable<int> store_status, Nullable<int> store_Id)
        {
            var store_NameParameter = store_Name != null ?
                new ObjectParameter("Store_Name", store_Name) :
                new ObjectParameter("Store_Name", typeof(string));
    
            var store_statusParameter = store_status.HasValue ?
                new ObjectParameter("store_status", store_status) :
                new ObjectParameter("store_status", typeof(int));
    
            var store_IdParameter = store_Id.HasValue ?
                new ObjectParameter("store_Id", store_Id) :
                new ObjectParameter("store_Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Store", store_NameParameter, store_statusParameter, store_IdParameter);
        }
    
        public virtual ObjectResult<ViewAll_Stores_Result> ViewAll_Stores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ViewAll_Stores_Result>("ViewAll_Stores");
        }
    
        public virtual ObjectResult<SP_SaveBrand_Result> SP_SaveBrand(Nullable<int> id, string name, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveBrand_Result>("SP_SaveBrand", idParameter, nameParameter, statusParameter);
        }
    
        public virtual ObjectResult<SP_SaveCategory_Result> SP_SaveCategory(Nullable<int> id, string name, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveCategory_Result>("SP_SaveCategory", idParameter, nameParameter, statusParameter);
        }
    
        public virtual ObjectResult<SP_SaveGroup_Result> SP_SaveGroup(Nullable<int> id, string name, string menus)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var menusParameter = menus != null ?
                new ObjectParameter("Menus", menus) :
                new ObjectParameter("Menus", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveGroup_Result>("SP_SaveGroup", idParameter, nameParameter, menusParameter);
        }
    
        public virtual ObjectResult<SP_SaveStore_Result> SP_SaveStore(Nullable<int> id, string name, Nullable<bool> status)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveStore_Result>("SP_SaveStore", idParameter, nameParameter, statusParameter);
        }
    
        public virtual ObjectResult<SP_SaveSupplier_Result> SP_SaveSupplier(Nullable<int> id, string name, string serviceCharge, string vat, string address, string phone, string country, string message, string currency)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var serviceChargeParameter = serviceCharge != null ?
                new ObjectParameter("ServiceCharge", serviceCharge) :
                new ObjectParameter("ServiceCharge", typeof(string));
    
            var vatParameter = vat != null ?
                new ObjectParameter("Vat", vat) :
                new ObjectParameter("Vat", typeof(string));
    
            var addressParameter = address != null ?
                new ObjectParameter("Address", address) :
                new ObjectParameter("Address", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var countryParameter = country != null ?
                new ObjectParameter("Country", country) :
                new ObjectParameter("Country", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("Message", message) :
                new ObjectParameter("Message", typeof(string));
    
            var currencyParameter = currency != null ?
                new ObjectParameter("Currency", currency) :
                new ObjectParameter("Currency", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveSupplier_Result>("SP_SaveSupplier", idParameter, nameParameter, serviceChargeParameter, vatParameter, addressParameter, phoneParameter, countryParameter, messageParameter, currencyParameter);
        }
    
        public virtual ObjectResult<SP_SaveUser_Result> SP_SaveUser(Nullable<int> id, string firstName, string lastName, string gender, string phone, string password, string emailId, Nullable<int> groupId, Nullable<bool> isActive)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var genderParameter = gender != null ?
                new ObjectParameter("Gender", gender) :
                new ObjectParameter("Gender", typeof(string));
    
            var phoneParameter = phone != null ?
                new ObjectParameter("Phone", phone) :
                new ObjectParameter("Phone", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var emailIdParameter = emailId != null ?
                new ObjectParameter("EmailId", emailId) :
                new ObjectParameter("EmailId", typeof(string));
    
            var groupIdParameter = groupId.HasValue ?
                new ObjectParameter("GroupId", groupId) :
                new ObjectParameter("GroupId", typeof(int));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("IsActive", isActive) :
                new ObjectParameter("IsActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SaveUser_Result>("SP_SaveUser", idParameter, firstNameParameter, lastNameParameter, genderParameter, phoneParameter, passwordParameter, emailIdParameter, groupIdParameter, isActiveParameter);
        }
    }
}
